### ISSUE TITLE
Erreur

### ISSUE THREAD

**Issue by SoLRB** [projets3scrum/Scrum#1]
Hey bonjour Mathilde, "Voulez" s'écrit "ez" à la fin. 
Bonne journée à toi :')

Sophiane.

**Comment by TomCelestin** [comment]
Oui.

**Comment by PechdiMathilde** [comment]
Bonjour , 

Je n'avais pas vu, merci je vais de ce pas le corriger ~.

Cordialement, 

Mathilde.
